# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\DEV\Py\doubleRep\p1UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 661)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbl_fname = QtWidgets.QListWidget(self.centralwidget)
        self.tbl_fname.setGeometry(QtCore.QRect(20, 20, 951, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_fname.sizePolicy().hasHeightForWidth())
        self.tbl_fname.setSizePolicy(sizePolicy)
        self.tbl_fname.setObjectName("tbl_fname")
        item = QtWidgets.QListWidgetItem()
        self.tbl_fname.addItem(item)
        self.tbl_details = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_details.setGeometry(QtCore.QRect(20, 410, 951, 151))
        self.tbl_details.setObjectName("tbl_details")
        self.tbl_details.setColumnCount(8)
        self.tbl_details.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_details.setHorizontalHeaderItem(7, item)
        self.btn_analyse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_analyse.setGeometry(QtCore.QRect(20, 380, 441, 23))
        self.btn_analyse.setObjectName("btn_analyse")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(904, 570, 61, 41))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_rename = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rename.setGeometry(QtCore.QRect(386, 570, 151, 23))
        self.btn_rename.setObjectName("btn_rename")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(556, 570, 151, 23))
        self.btn_delete.setObjectName("btn_delete")
        self.btn_show = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show.setGeometry(QtCore.QRect(220, 570, 151, 23))
        self.btn_show.setObjectName("btn_show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.tbl_fname.isSortingEnabled()
        self.tbl_fname.setSortingEnabled(False)
        item = self.tbl_fname.item(0)
        item.setText(_translate("MainWindow", "vereinheitlichter FilmName"))
        self.tbl_fname.setSortingEnabled(__sortingEnabled)
        item = self.tbl_details.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "lfd.Nr."))
        item = self.tbl_details.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FilmDatei"))
        item = self.tbl_details.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Typ"))
        item = self.tbl_details.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Größe"))
        item = self.tbl_details.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Datum"))
        item = self.tbl_details.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "VideoAuflösung"))
        item = self.tbl_details.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Audio-Streams"))
        item = self.tbl_details.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Subtitles"))
        self.btn_analyse.setText(_translate("MainWindow", "Analyse   (Strg+a, DblClick, F2)"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.btn_rename.setText(_translate("MainWindow", "Umbenennen  (F6)"))
        self.btn_delete.setText(_translate("MainWindow", "Löschen  (Entf)"))
        self.btn_show.setText(_translate("MainWindow", "Abspielen  (Enter)"))
